# Generated by Django 4.2.3 on 2023-08-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_contactus_position_course_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='samplevideo',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='staffdetail',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='staffdetail',
            name='experience',
            field=models.CharField(default='', max_length=100, verbose_name='Experience'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffdetail',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='staffdetail',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='contactus',
            unique_together={('page_id', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('page_id', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='coursecategory',
            unique_together={('page_id', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='faq',
            unique_together={('page_id', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('page_id', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='samplevideo',
            unique_together={('page_id', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='staffdetail',
            unique_together={('page_id', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='testimonial',
            unique_together={('page_id', 'position')},
        ),
    ]
